---
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: helm-kubectl
      image: kmdr7/helm-kubectl:latest
      command: ["tail", "-f", "/dev/null"]
    - name: docker
      image: docker:18.06.1
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
        mountPath: /var/run/docker.sock
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - kube-worker-1